# Generated by Django 2.2.28 on 2023-07-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsite',
            name='is_show',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否展示'),
        ),
        migrations.AddField(
            model_name='navigationsite',
            name='not_show_reason',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='禁用原因'),
        ),
    ]
