# Generated by Django 2.2.28 on 2023-07-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstack', '0002_auto_20230724_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstmenu',
            name='icon',
            field=models.CharField(help_text='Font Awesome图标库格式，如:fa fa-star-o', max_length=30, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='secondmenu',
            name='icon',
            field=models.CharField(help_text='Font Awesome图标库格式，如:fa fa-star-o', max_length=30, verbose_name='图标'),
        ),
    ]
